name: Publish

on:
  push:
    tags:
      - "*.*.*"
jobs:
  publish:
    runs-on: macOS

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Install Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn

      - name: Package releases
        run: |
          yarn postinstall
          yarn build
          yarn package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/build/*.dmg
            release/build/*.exe
